networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - game
      - frontend
       
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./key.pem:/root/ssl/key.pem"
      - "./cert.pem:/root/ssl/cert.pem"
    networks:
      - dev
    platform: linux/amd64
    restart: always


  game:
    build:
      context: ./game
    networks:
      - dev
    platform: linux/amd64
    ports:
      - "8080:80"
    restart: always
      
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    platform: linux/amd64
    ports:
      - "3000:80"
    restart: always