networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - game
      - frontend
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - dev
    platform: linux/arm64

  game:
    build:
      context: ./game
    networks:
      - dev
    platform: linux/arm64
      
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    platform: linux/arm64