networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - game
      - frontend
       
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html"
    networks:
      - dev
    platform: linux/amd64
    restart: always

  # certbot:
  #   image: certbot/certbot:latest
  #   container_name: certbot
  #   depends_on:
  #     - nginx
  #   networks:
  #     - dev
  #   volumes:
  #     - "./certbot/conf:/etc/letsencrypt"
  #     - "./certbot/www:/usr/share/nginx/html"
  #   #command: certonly --webroot --webroot-path /usr/share/nginx/html --dry-run --force-renewal --email rmnsfx@gmail.com --agree-tos --no-eff-email -d valentures.ru -d www.valentures.ru
  #   command: certonly --webroot --webroot-path /usr/share/nginx/html --force-renewal --email rmnsfx@gmail.com --agree-tos --no-eff-email -d valentures.ru -d www.valentures.ru

  game:
    build:
      context: ./game
    networks:
      - dev
    platform: linux/amd64
    ports:
      - "8080:80"
    restart: always
      
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    platform: linux/amd64
    ports:
      - "3000:80"
    restart: always
    volumes:
      - "./certbot/conf:/etc/letsencrypt"
      - "./certbot/www:/usr/share/nginx/html"